import type { ChallengeKind, ObjectiveJson, RuleBuilder } from "./types";

function O(type: string, description: string, targetValue?: string): ObjectiveJson {
  return targetValue ? { type, description, targetValue } : { type, description };
}

export const TEAM_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `Projeto elite ${c.team.name}`,
    objectives: [O("league", `Classificar ${c.team.name} para fase de grupos europeia em até 2 temporadas.`)],
    restrictions: ["Priorizar reforços da mesma liga ou da mesma região do clube."],
    tacticNotes: ["Valorizar o miolo atual antes de trocas caras."],
    narrativeHints: [`${c.team.name} mira estabilidade no topo da pirâmide local.`],
  }),
  (c) => ({
    short: `Fuga ${c.team.name}`,
    objectives: [O("league", `Sair da zona de rebaixamento antes da rodada ${c.int(28, 36)} com ${c.team.name}.`)],
    restrictions: ["Não emprestar titulares na janela de inverno."],
    tacticNotes: ["Marcação mais baixa contra ataques diretos."],
    narrativeHints: ["A pressão da torcida pesa em cada empate."],
  }),
  (c) => ({
    short: `Copa ${c.team.name}`,
    objectives: [O("cup", `Alcançar pelo menos a semifinal da copa doméstica com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: ["Rotacionar no meio até as quartas de final."],
    narrativeHints: [`${c.team.name} troca prioridade da liga em prol da taça.`],
  }),
  (c) => ({
    short: `Rigor de forma`,
    objectives: [O("form", `No máximo ${c.int(2, 5)} derrotas na liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: ["Disciplina tática extrema é cobrada pelo conselho."],
  }),
  (c) => ({
    short: `Underdog europeu`,
    objectives: [O("europe", `Chegar à fase eliminatória continental com ${c.team.name}.`)],
    restrictions: [`Na 1ª temporada, investir no máximo ${c.int(55, 85)}% do orçamento de transferências.`],
    tacticNotes: [],
    narrativeHints: [`${c.team.name} sonha alto com recursos modestos.`],
  }),
  (c) => ({
    short: `Título de liga`,
    objectives: [O("titles", `Vencer a liga nacional com ${c.team.name} em até ${c.int(3, 6)} temporadas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Zona europeia`,
    objectives: [O("league", `Terminar no top ${c.int(4, 8)} da liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Saneamento ${c.team.name}`,
    objectives: [O("finance", `Dois anos seguidos com resultado financeiro positivo em ${c.team.name}.`)],
    restrictions: ["Vender jogador se a oferta for ≥ 130% do valor de mercado nas janelas."],
    tacticNotes: [],
    narrativeHints: [`O conselho exige controle de caixa em ${c.team.name}.`],
  }),
  (c) => ({
    short: `Reta final quente`,
    objectives: [O("form", `Vencer ${c.int(5, 9)} dos últimos ${c.int(8, 10)} jogos de liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: ["Subir a linha defensiva nos minutos finais quando estiver atrás."],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Derby invicto`,
    objectives: [O("derby", `Não perder clássicos ou derbys regionais com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Renovação ${c.team.name}`,
    objectives: [O("squad", `Média de idade do onze inicial ≤ ${c.int(24, 27)} anos na segunda metade da temporada.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Goleada coletiva`,
    objectives: [O("goals", `Marcar ${c.int(60, 95)} gols na liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Muro atrás`,
    objectives: [O("defense", `Sofrer menos de ${c.int(35, 48)} gols na liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: ["Bloco médio-baixo fora de casa contra times fortes."],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Elenco enxuto`,
    objectives: [O("squad", `Manter no máximo ${c.int(22, 26)} jogadores no plantel de ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Fortaleza em casa`,
    objectives: [O("home", `Pelo menos ${c.int(11, 16)} vitórias em casa na liga com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Calendário europeu`,
    objectives: [
      O(
        "fitness",
        `Após rodadas europeias, não perder o jogo seguinte de liga com ${c.team.name} (${c.int(4, 7)} oportunidades).`,
      ),
    ],
    restrictions: [],
    tacticNotes: ["Planejar rotação após Champions ou Europa League."],
    narrativeHints: [],
  }),
];

export const PLAYER_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `${c.player.name} artilharia`,
    objectives: [O("player_goals", `${c.player.name}: mínimo ${c.int(14, 30)} gols na temporada.`, String(c.int(14, 30)))],
    restrictions: [`${c.player.name} deve iniciar ${c.int(28, 38)} jogos como titular.`],
    tacticNotes: [],
    narrativeHints: [`O projeto ofensivo orbita ${c.player.name}.`],
  }),
  (c) => ({
    short: `Braçadeira ${c.player.name}`,
    objectives: [O("captain", `${c.player.name} deve ser capitão em pelo menos ${c.int(22, 36)} partidas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Garçom ${c.player.name}`,
    objectives: [O("assists", `${c.player.name}: ${c.int(9, 22)} assistências na temporada.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Evolução ${c.player.name}`,
    objectives: [O("growth", `Aumentar o overall de ${c.player.name} em +${c.int(2, 6)} ao longo do save.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Referência ${c.player.name}`,
    objectives: [O("award", `${c.player.name} entre os 3 melhores do clube em participações (gol + assistência).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Minutos absolutos`,
    objectives: [O("minutes", `${c.player.name} deve liderar minutos em campo no elenco do ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Função ${c.player.position}`,
    objectives: [O("role", `${c.player.name}: ${c.int(18, 32)} jogos compondo a formação como ${c.player.position}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Bola parada`,
    objectives: [O("setpiece", `${c.player.name} cobrador titular de escanteios e faltas perigosas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `${c.player.name} em casa`,
    objectives: [O("player_home", `${c.player.name} participa de gol em ${c.int(12, 22)} jogos em casa.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Hat-trick`,
    objectives: [O("hattrick", `${c.player.name} deve marcar pelo menos um hat-trick na temporada.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Limite de cartão`,
    objectives: [O("cards", `${c.player.name}: no máximo ${c.int(5, 10)} cartões amarelos na liga.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Super-reserva`,
    objectives: [
      O(
        "supersub",
        `${c.player.name}: entrando no 2º tempo, marcar ou assistir ${c.int(5, 12)} vezes.`,
      ),
    ],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Impedível`,
    objectives: [O("rating", `${c.player.name}: média de nota ≥ ${(7 + c.int(0, 4) / 10).toFixed(1)} nos dados do modo carreira.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Libertadores do craque`,
    objectives: [O("europe_player", `${c.player.name} deve marcar ou assistir ${c.int(4, 10)} gols em mata-mata continental.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Contrato moral`,
    objectives: [O("morale", `Manter ${c.player.name} "feliz" ou equivalente por ${c.int(24, 34)} semanas seguidas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Pênaltis`,
    objectives: [O("penalties", `${c.player.name} cobrador oficial; converter ${c.int(4, 9)} de ${c.int(5, 11)} cobranças simuladas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const TACTICAL_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `Esquema ${c.formation}`,
    objectives: [O("formation", `Usar ${c.formation} como esquema base em ${c.int(26, 38)} jogos de liga.`)],
    restrictions: [],
    tacticNotes: [`Formação fixa: ${c.formation}.`],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Estilo ${c.style}`,
    objectives: [O("style", `Instruções devem refletir jogo ${c.style} na maior parte da temporada.`)],
    restrictions: [],
    tacticNotes: [`Estilo predominante: ${c.style}.`],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Três zagueiros`,
    objectives: [O("def_line", `Manter linha com três defensores centrais em todos os jogos oficiais.`)],
    restrictions: [],
    tacticNotes: ["Adaptar alas para funcionar como pontas ou alas largos."],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Linha alta`,
    objectives: [O("line", `Defender com linha defensiva alta em pelo menos ${c.int(18, 34)} partidas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Posse ${c.int(58, 68)}%`,
    objectives: [O("possession", `Alcançar posse média ≥ ${c.int(58, 68)}% em blocos de 10 jogos de liga (ao menos 3 blocos).`)],
    restrictions: [],
    tacticNotes: ["Priorizar meias que saem para jogo."],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Transição rápida`,
    objectives: [O("trans", `Configurar bloco médio e ataque direto em ${c.int(20, 32)} jogos.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Pressão alta`,
    objectives: [O("press", `Pressão alta após perda em ${c.int(22, 36)} jogos consecutivos ou alternados.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Extremos invertidos`,
    objectives: [O("width", `Usar extremos no pé "errado" como padrão tático.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Volante fixo`,
    objectives: [O("dm", `Dois volantes de contenção de partida em ${c.int(24, 34)} jogos.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Laterais ofensivos`,
    objectives: [O("fbs", `Laterais com instrução de subir em ${c.int(28, 38)} jogos.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Falso nove`,
    objectives: [O("false9", `Utilizar falso 9 ou ponta centralizado em ${c.int(15, 28)} jogos.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Zonal puro`,
    objectives: [O("zonal", `Marcação de bola parada zonal em todas as temporadas do desafio.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Saída curta`,
    objectives: [O("build", `Sempre que possível: saída de bola curta com goleiro.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Bloco baixo`,
    objectives: [O("low", `Retranca organizada (bloco baixo) em ${c.int(12, 22)} jogos contra big six da liga.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Duas linhas de quatro`,
    objectives: [O("flat", `Dois bancos de quatro sem meia solto clássico em ${c.int(18, 30)} jogos.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const FINANCIAL_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `Zero compras`,
    objectives: [O("finance", `Não gastar em compras de transferência por ${c.int(1, 2)} janela(s) seguida(s).`)],
    restrictions: ["Proibido pagar valor de transferência; apenas empréstimos livres ou jogadores livres."],
    tacticNotes: [],
    narrativeHints: [`Caixa congelado — ${c.team.name} vive do que já tem.`],
  }),
  (c) => ({
    short: `Venda agressiva`,
    objectives: [O("sell", `Arrecadar ${c.int(18, 45)}M em vendas acumuladas em duas janelas.`)],
    restrictions: ["Aceitar proposta se pagar ≥ 120% do valor de mercado."],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Saldo verde`,
    objectives: [O("balance", `Encerrar cada temporada com saldo de caixa maior que o início.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Orçamento ${c.int(15, 40)}M`,
    objectives: [O("cap", `Não ultrapassar ${c.int(15, 40)}M líquidos gastos em transferências por temporada.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Folha contida`,
    objectives: [O("wage", `Manter folha salarial abaixo de ${c.int(100, 220)}% da receita de estádio simulada (via painel).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Cash positivo`,
    objectives: [O("finance", `Caixa nunca negativo após qualquer disputa de janela.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Sem agentes caros`,
    objectives: [O("signing", `Não contratar jogador com valor ${">"}= ${c.int(45, 85)}M.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Lucro na base`,
    objectives: [O("youth_sale", `Lucrar ${c.int(25, 60)}M só com vendas de jogadores formados no clube ou sub-21.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Multas rescisão`,
    objectives: [O("clause", `Não ativar cláusulas de rescisão acima de ${c.int(35, 90)}M.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Empréstimos só`,
    objectives: [O("loan_only", `Reforços apenas via empréstimo com opção de compra abaixo de ${c.int(15, 35)}M.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Venda estrela`,
    objectives: [O("sell_star", `Se receber oferta irrecusável (${
      c.int(2, 4)
    }× valor de mercado), vender o ativo mais caro do elenco.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Juros zero`,
    objectives: [O("debt", `Não usar empréstimo do clube (se existir no modo) durante o desafio.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Patrocínio`,
    objectives: [O("commercial", `Negociar melhoria comercial anual (objetivo interno de diretoria) ${c.int(2, 4)} vezes.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const YOUTH_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `3 da base`,
    objectives: [O("youth_start", `Iniciar ${c.int(3, 5)} jogadores da base ou YA em ${c.int(22, 32)} jogos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [`${c.team.name} precisa sangue novo urgente.`],
  }),
  (c) => ({
    short: `Sub-21 only`,
    objectives: [O("u21", `Contratar apenas jogadores com ${"<="} 21 anos nas janelas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Promissões +${c.int(3, 7)}`,
    objectives: [O("grow_youth", `Elevar pelo menos ${c.int(3, 7)} jovens do elenco em +3 de overall cada.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Scouts agressivos`,
    objectives: [O("scout", `Manter ${c.int(2, 4)} olheiros ativos em regiões distintas o tempo todo.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Titular sub-${c.int(19, 22)}`,
    objectives: [O("young_xi", `Média de idade titular ${"<="} ${c.int(22, 24)} em ${c.int(16, 28)} jogos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Reserva experiência`,
    objectives: [O("mentor", `Máximo ${c.int(2, 4)} jogadores acima de 30 anos no plantel.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `YA produtivo`,
    objectives: [O("ya", `Promover ${c.int(2, 4)} jogadores da academia ao time principal em ${c.int(1, 2)} temporada(s).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Vender veterano`,
    objectives: [O("turnover", `Vender ${c.int(2, 4)} jogadores acima de ${c.int(29, 32)} anos para abrir espaço.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Recompra`,
    objectives: [O("sell_buy", `Lucrar com venda de jovem e reinvestir só em outro sub-23.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Minutos jovens`,
    objectives: [O("mins", `Jogadores ${"<="} 23 anos somam ${c.int(45, 70)}% dos minutos totais do clube.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Potencial ouro`,
    objectives: [O("pot", `Contratar ${c.int(2, 4)} jogadores com potential ${">="} ${c.int(84, 92)}.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Banco jovem`,
    objectives: [O("bench", `Substituições: priorizar jogadores ${"<="} 23 anos em ${c.int(28, 38)} jogos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Pré-temporada base`,
    objectives: [O("pretrip", `Convocar ${c.int(6, 10)} jogadores da base para pré-temporada longa.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const HARDCORE_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `2 contratações / janela`,
    objectives: [O("transfer_cap", `Máximo de 2 jogadores comprados por janela de transferência.`)],
    restrictions: ["Free transfers e empréstimos contam no limite."],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Sem subs`,
    objectives: [O("no_subs", `Não usar substituições em ${c.int(8, 16)} jogos espalhados pela temporada.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Escalação única`,
    objectives: [O("unique_xi", `Não repetir o mesmo onze titular em jogos consecutivos de liga.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Esquema fixo`,
    objectives: [O("fixed_form", `Não mudar formação (${c.formation}) durante ${c.int(34, 38)} jogos de liga.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Sem reload`,
    objectives: [O("ironman", `Jogar sem recarregar partidas salvas (honra — anotar internamente).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Lesão = drama`,
    objectives: [O("injury", `Se um titular se lesionar ${">"} ${c.int(3, 6)} semanas, não substituí-lo por reforço na mesma posição.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Táticas travadas`,
    objectives: [O("locked", `Não alterar instruções individuais após a 10ª rodada até o fim do turno.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Venda forçada`,
    objectives: [O("forced_sale", `Se qualquer proposta ≥ ${c.int(140, 200)}% do valor chegar, aceitar.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Um só país`,
    objectives: [O("nation", `Plantel com jogadores de no máximo ${c.int(6, 10)} nacionalidades diferentes.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Fair play`,
    objectives: [O("discipline", `Terminar liga com no máximo ${c.int(50, 75)} cartões amarelos acumulados.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Sem treino individual`,
    objectives: [O("training", `Não usar treinos individuais focados (se aplicável ao modo) durante 1 temporada.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Reserva titular`,
    objectives: [O("rotation", `Nenhum jogador pode iniciar ${">"} ${c.int(84, 92)}% dos jogos da temporada.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Limitar estrelas`,
    objectives: [O("stars", `No máximo ${c.int(2, 4)} jogadores com overall ${">"}= ${c.int(84, 88)} no XI médio.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Simulação mínima`,
    objectives: [O("sim", `Simular no máximo ${c.int(4, 10)} jogos de liga na temporada; o resto jogado.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Goleiro único`,
    objectives: [O("gk", `Mesmo goleiro em todos os jogos oficiais da temporada (salvo lesão prolongada).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const STORY_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `Crise em ${c.team.name}`,
    objectives: [O("story", `Narrativa: crise financeira; aposta em jovens para sobreviver com ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [
      `O clube enfrenta crise financeira e aposta em jovens talentos para sobreviver — foco em ${c.team.name}.`,
    ],
  }),
  (c) => ({
    short: `Herói local`,
    objectives: [O("story", `Construir time com maioria de jogadores da mesma nacionalidade do país de ${c.team.name}.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: ["A torcida quer um time que represente o orgulho local."],
  }),
  (c) => ({
    short: `Segunda chance`,
    objectives: [O("story", `Contratar ${c.int(2, 4)} jogadores em má fase de forma ou em rejeição na carreira — dar minutos reais.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Legado`,
    objectives: [O("story", `Cumprir ${c.int(2, 3)} temporadas seguidas com título ou top ${c.int(3, 6)} antes de sair do clube.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [`${c.player.name} e o elenco escrevem um novo capítulo de ${c.team.name}.`],
  }),
  (c) => ({
    short: `O exiled`,
    objectives: [O("story", `Reerguer carreira saindo de um clube grande para ${c.team.name} sem reforços de elite no 1º ano.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Redenção`,
    objectives: [O("story", `Após temporada vexatória simulada, não perder em casa nas ${c.int(10, 18)} primeiras partidas do ano.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Mentor técnico`,
    objectives: [O("story", `Prometer minutos a ${c.int(2, 3)} jovens e cumprir — narrativa de "professor".`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Rival interno`,
    objectives: [O("story", `Conter o jogador mais caro do elenco em minutos até ele "aceitar" reserva (via narrativa sua).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Fênix`,
    objectives: [O("story", `Subir divisional ou sair de zona de rebaixamento e classificar para copa no ano seguinte.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Adepto digital`,
    objectives: [O("story", `Objetivo de humor: bater meta de "expectativas da diretoria" em ${c.int(3, 5)} checagens seguidas.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Tapeçaria`,
    objectives: [O("story", `Montar elenco de ${c.int(9, 14)} nacionalidades diferentes mantendo química (objetivo pessoal).`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Queda e subida`,
    objectives: [O("story", `Sofrer eliminação cedo em copa mas compensar com campanha perfeita em liga nas últimas ${c.int(8, 12)} rodadas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const CHAOS_BUILDERS: RuleBuilder[] = [
  (c) => ({
    short: `Capitão rotativo`,
    objectives: [O("chaos_cap", `Trocar o capitão a cada jogo oficial por ${c.int(12, 28)} partidas consecutivas.`)],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: ["Imprevisibilidade total na liderança."],
  }),
  (c) => ({
    short: `Aleatório titular`,
    objectives: [
      O("random_starter", `Antes de ${c.int(15, 25)} jogos, sortear um titular obrigatório entre não-goleiros do elenco.`),
    ],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Venda melhor`,
    objectives: [O("chaos_sell", `Ao fim da temporada ${c.int(1, 3)}, vender o jogador com maior overall do elenco.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Mudar formação`,
    objectives: [O("chaos_form", `Alterar esquema tático a cada jogo de liga por ${c.int(8, 16)} jogos seguidos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Inversão`,
    objectives: [O("chaos_inv", `Em ${c.int(4, 8)} jogos, inverter o lado dos extremos e laterais na escalação.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Sorteio substituições`,
    objectives: [O("chaos_sub", `Ordem das substituições decidida por dado (1-3) em ${c.int(10, 20)} jogos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Fair play inverso`,
    objectives: [O("chaos_rough", `Receber pelo menos ${c.int(60, 95)} faltas sofridas na temporada (estilo "provocador").`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Calendário louco`,
    objectives: [
      O(
        "chaos_sched",
        `Jogar com intensidade "ultra ofensiva" nas idas e "ultra defensiva" nas voltas em duelos de mata-mata (se houver).`,
      ),
    ],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Multibalões`,
    objectives: [O("chaos_ball", `Kicker de bola diferente por jogo em ${c.int(10, 18)} partidas.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Herói aleatório`,
    objectives: [O("chaos_hero", `Sortear um reserva para titularidade surpresa em ${c.int(6, 14)} jogos.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Zebra obrigatória`,
    objectives: [
      O(
        "chaos_upset",
        `Vencer pelo menos ${c.int(2, 4)} jogos contra clubes com elenco mais forte (overall médio maior) que ${c.team.name}.`,
      ),
    ],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Treinador maluco`,
    objectives: [O("chaos_rage", `Aplicar "estilo ultra" pressão ou retranca alternados a cada jogo por ${c.int(10, 20)} rodadas.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Escanteio curto`,
    objectives: [O("chaos_corner", `Sempre escanteio curto em ${c.int(20, 34)} jogos — sem exceção.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Goleiro chuta`,
    objectives: [O("chaos_gk", `Goleiro em bola parada ofensiva nos últimos ${c.int(4, 9)} minutos quando perdendo.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Inversão de braçadeira`,
    objectives: [O("chaos_vice", `${c.player.name} capitão em exatos ${c.int(5, 12)} jogos espalhados no ano.`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
  (c) => ({
    short: `Ordem alfabética`,
    objectives: [O("chaos_alpha", `Em ${c.int(3, 6)} jogos, escalar os titulares pela ordem alfabética do sobrenome (modo desafio).`),],
    restrictions: [],
    tacticNotes: [],
    narrativeHints: [],
  }),
];

export const BUILDERS_BY_KIND: Record<ChallengeKind, RuleBuilder[]> = {
  TEAM: TEAM_BUILDERS,
  PLAYER: PLAYER_BUILDERS,
  TACTICAL: TACTICAL_BUILDERS,
  FINANCIAL: FINANCIAL_BUILDERS,
  YOUTH: YOUTH_BUILDERS,
  HARDCORE: HARDCORE_BUILDERS,
  STORY: STORY_BUILDERS,
  CHAOS: CHAOS_BUILDERS,
};
