/** Desafios predefinidos (catalogo) — sem times/jogadores fixos; o usuario aplica no save. */
export type PresetChallengeInput = {
  name: string;
  difficulty: "easy" | "medium" | "hard";
  type: string[];
  objectives: string[];
  restrictions: string[];
};

export const PRESET_CHALLENGE_INPUTS: PresetChallengeInput[] = [
  {
    name: "Projeto Mbappé",
    difficulty: "hard",
    type: ["Player"],
    objectives: ["40 gols", "Champions League"],
    restrictions: ["Sempre titular", "Não substituir antes dos 70"],
  },
  {
    name: "Era Haaland",
    difficulty: "easy",
    type: ["Player"],
    objectives: ["50 gols"],
    restrictions: ["Jogo ofensivo obrigatório"],
  },
  {
    name: "Messi Maestro",
    difficulty: "medium",
    type: ["Player", "Tactical"],
    objectives: ["25 assistências"],
    restrictions: ["Sempre como CAM"],
  },
  {
    name: "Neymar Redenção",
    difficulty: "medium",
    type: ["Player"],
    objectives: ["20 gols + 15 assistências"],
    restrictions: ["Não vender"],
  },
  {
    name: "CR7 Última Dança",
    difficulty: "hard",
    type: ["Player"],
    objectives: ["Artilheiro da liga"],
    restrictions: ["Sempre titular"],
  },
  {
    name: "Reconstrução Total",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Top 6"],
    restrictions: ["3 contratações por janela"],
  },
  {
    name: "Gigante em Crise",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Voltar à Champions"],
    restrictions: ["Orçamento limitado"],
  },
  {
    name: "Time Invencível",
    difficulty: "hard",
    type: ["Team"],
    objectives: ["Liga invicta"],
    restrictions: ["Sem repetir escalação"],
  },
  {
    name: "Domínio Nacional",
    difficulty: "easy",
    type: ["Team"],
    objectives: ["Ganhar liga"],
    restrictions: [],
  },
  {
    name: "Triplete",
    difficulty: "hard",
    type: ["Team"],
    objectives: ["Liga + Copa + Champions"],
    restrictions: [],
  },
  {
    name: "Só Jovens",
    difficulty: "hard",
    type: ["Youth"],
    objectives: ["Top 6"],
    restrictions: ["Só sub-23"],
  },
  {
    name: "Base Forte",
    difficulty: "medium",
    type: ["Youth"],
    objectives: ["3 titulares da base"],
    restrictions: ["Sem veteranos"],
  },
  {
    name: "Projeto Sub-21",
    difficulty: "hard",
    type: ["Youth"],
    objectives: ["Evoluir jogadores"],
    restrictions: ["Sem contratar acima de 21"],
  },
  {
    name: "Academia FC",
    difficulty: "hard",
    type: ["Youth"],
    objectives: ["Top 8"],
    restrictions: ["Só base"],
  },
  {
    name: "Futuro do Clube",
    difficulty: "medium",
    type: ["Youth"],
    objectives: ["2 jovens +80 overall"],
    restrictions: [],
  },
  {
    name: "Sem Dinheiro",
    difficulty: "hard",
    type: ["Financial"],
    objectives: ["Top 5"],
    restrictions: ["Sem transferências"],
  },
  {
    name: "Moneyball",
    difficulty: "medium",
    type: ["Financial"],
    objectives: ["Lucro"],
    restrictions: ["Comprar barato vender caro"],
  },
  {
    name: "Orçamento Zero",
    difficulty: "hard",
    type: ["Financial"],
    objectives: ["Top 6"],
    restrictions: ["Sem gastar"],
  },
  {
    name: "Free Agents Only",
    difficulty: "hard",
    type: ["Financial"],
    objectives: ["Top 5"],
    restrictions: ["Só jogadores livres"],
  },
  {
    name: "Venda Obrigatória",
    difficulty: "medium",
    type: ["Financial"],
    objectives: ["Top 4"],
    restrictions: ["Vender melhor jogador"],
  },
  {
    name: "Pressão Total",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 3 gols"],
    restrictions: ["Pressão alta sempre"],
  },
  {
    name: "Contra-Ataque Mortal",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 3"],
    restrictions: ["Contra-ataque"],
  },
  {
    name: "Posse Absoluta",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["60% posse"],
    restrictions: ["Jogo lento"],
  },
  {
    name: "Retranca Máxima",
    difficulty: "hard",
    type: ["Tactical"],
    objectives: ["Menos gols sofridos"],
    restrictions: ["Linha baixa"],
  },
  {
    name: "3 Zagueiros Sempre",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 4"],
    restrictions: ["3-5-2 obrigatório"],
  },
  {
    name: "Modo Caos",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 6"],
    restrictions: ["Formação aleatória"],
  },
  {
    name: "Sem Substituições",
    difficulty: "hard",
    type: ["Hardcore"],
    objectives: ["Ganhar título"],
    restrictions: ["Sem subs"],
  },
  {
    name: "Rotação Total",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 4"],
    restrictions: ["Escalação nova todo jogo"],
  },
  {
    name: "Sem Zagueiros",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 8"],
    restrictions: ["Sem CB"],
  },
  {
    name: "Sem Laterais",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 6"],
    restrictions: ["Sem LB/RB"],
  },
  {
    name: "Só Brasileiros",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Top 3"],
    restrictions: ["Só BR"],
  },
  {
    name: "Só Europeus",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Top 4"],
    restrictions: ["Só Europa"],
  },
  {
    name: "Só Africanos",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Top 5"],
    restrictions: ["Só África"],
  },
  {
    name: "Time Local",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Top 6"],
    restrictions: ["Mesma nacionalidade"],
  },
  {
    name: "Mistura Global",
    difficulty: "easy",
    type: ["Team"],
    objectives: ["Top 4"],
    restrictions: [],
  },
  {
    name: "Capitão Líder",
    difficulty: "medium",
    type: ["Player"],
    objectives: ["Ser capitão"],
    restrictions: ["Sempre titular"],
  },
  {
    name: "Hat-Trick King",
    difficulty: "medium",
    type: ["Player"],
    objectives: ["3 hat-tricks"],
    restrictions: [],
  },
  {
    name: "Playmaker Master",
    difficulty: "medium",
    type: ["Player"],
    objectives: ["20 assistências"],
    restrictions: ["CAM obrigatório"],
  },
  {
    name: "Artilheiro Supremo",
    difficulty: "medium",
    type: ["Player"],
    objectives: ["30 gols"],
    restrictions: [],
  },
  {
    name: "Jogador de Ferro",
    difficulty: "hard",
    type: ["Player"],
    objectives: ["Jogar todos jogos"],
    restrictions: ["Sem descanso"],
  },
  {
    name: "Time Alto",
    difficulty: "medium",
    type: ["Chaos"],
    objectives: ["Top 5"],
    restrictions: ["Só >1.80m"],
  },
  {
    name: "Time Baixo",
    difficulty: "medium",
    type: ["Chaos"],
    objectives: ["Top 5"],
    restrictions: ["Só baixos"],
  },
  {
    name: "Só Velocistas",
    difficulty: "medium",
    type: ["Chaos"],
    objectives: ["Top 4"],
    restrictions: ["Só pace alto"],
  },
  {
    name: "Só Lentos",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 6"],
    restrictions: ["Sem velocidade"],
  },
  {
    name: "Time Técnico",
    difficulty: "medium",
    type: ["Chaos"],
    objectives: ["Top 4"],
    restrictions: ["Só dribladores"],
  },
  {
    name: "Sem Volante",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 8"],
    restrictions: ["Sem CDM"],
  },
  {
    name: "Sem Ataque",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 10"],
    restrictions: ["Sem ST"],
  },
  {
    name: "Sem Meio",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 8"],
    restrictions: ["Sem CM"],
  },
  {
    name: "Defesa Total",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Menos gols sofridos"],
    restrictions: [],
  },
  {
    name: "Ataque Total",
    difficulty: "easy",
    type: ["Tactical"],
    objectives: ["Mais gols"],
    restrictions: [],
  },
  {
    name: "Desafio Improvável",
    difficulty: "hard",
    type: ["Story"],
    objectives: ["Top 4"],
    restrictions: ["Sem estrelas"],
  },
  {
    name: "Lenda do Clube",
    difficulty: "hard",
    type: ["Player"],
    objectives: ["200 jogos"],
    restrictions: ["Não vender"],
  },
  {
    name: "Salvador",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Evitar rebaixamento"],
    restrictions: [],
  },
  {
    name: "Dominar Europa",
    difficulty: "hard",
    type: ["Team"],
    objectives: ["Champions"],
    restrictions: [],
  },
  {
    name: "Copa Mestre",
    difficulty: "medium",
    type: ["Team"],
    objectives: ["Ganhar copa"],
    restrictions: [],
  },
  {
    name: "Formação Fixa",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 4"],
    restrictions: ["Mesma formação sempre"],
  },
  {
    name: "Troca Constante",
    difficulty: "hard",
    type: ["Chaos"],
    objectives: ["Top 5"],
    restrictions: ["Trocar formação"],
  },
  {
    name: "Pressão Máxima",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 3"],
    restrictions: ["Linha alta"],
  },
  {
    name: "Linha Baixa",
    difficulty: "medium",
    type: ["Tactical"],
    objectives: ["Top 6"],
    restrictions: ["Retranca"],
  },
  {
    name: "Equilíbrio Total",
    difficulty: "easy",
    type: ["Tactical"],
    objectives: ["Top 4"],
    restrictions: [],
  },
  {
    name: "Venda Constante",
    difficulty: "hard",
    type: ["Financial"],
    objectives: ["Top 6"],
    restrictions: ["Vender 1 por janela"],
  },
  {
    name: "Sem Compras",
    difficulty: "hard",
    type: ["Financial"],
    objectives: ["Top 5"],
    restrictions: ["Sem compras"],
  },
  {
    name: "Lucro Máximo",
    difficulty: "medium",
    type: ["Financial"],
    objectives: ["+50M lucro"],
    restrictions: [],
  },
  {
    name: "Mercado Restrito",
    difficulty: "medium",
    type: ["Financial"],
    objectives: ["Top 6"],
    restrictions: ["Só empréstimos"],
  },
  {
    name: "Equipe Barata",
    difficulty: "medium",
    type: ["Financial"],
    objectives: ["Top 5"],
    restrictions: ["Baixo custo"],
  },
];
